### ISSUE TITLE
QL-720NW

### ISSUE THREAD

**Issue by ghost** [talpadk/ptouch-php#2]
Hi,

I'm trying to use this with the QL-720NW model.
The project is to generate a PRN file and send it to the printer using FTP.
An idea?

Thanks,

Michael

**Comment by talpadk** [comment]
The software in this repository has been specifically written to interface over USB.
And as such it may not be the best candidate for generating PRN files.

However it seems that Brother does have public protocol information for that the QL-720NW
http://support.brother.com/g/b/manualtop.aspx?c=eu_ot&lang=en&prod=lpql720nweuk

The documentation for ESC/P for instance might be useful for generating data for the printer.
http://download.brother.com/welcome/docp000706/cv_ql720_eng_escp_100.pdf

**Comment by ghost** [comment]
Thanks.
I close this issue since we will be using the Windows driver.
